global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Reactivities.Api.Activities;
global using Reactivities.Api.Extensions;
global using Reactivities.Application.Activities;
global using Reactivities.Domain;
global using Reactivities.Persistence;
global using System.Diagnostics.CodeAnalysis;
